### PR TITLE
Add admin panel

### PR DESCRIPTION
**Pull request by etagwerker**
Hi there, 

This PR adds a panel interface to this project. It uses basic HTTP authentication to control access to it. 

Please check it out. 

Thanks!

### CODE REVIEW

**Comment by bronzdoc** [comment]
@etagwerker Why we need this?

**Comment by etagwerker** [comment]
@bronzdoc It will make it easier to see the reports and further develop insights based on files, skunk scores, churn, cost, etc... 

Right now it looks like this: 

Screen Shot 2021-02-10 at 2 28 10 PM

As part of the roadmap for this project I had these features in mind: 

- #30 
- #31 

The admin panel will help us work with data internally before we work with those features.

**Review by bronzdoc — COMMENTED** [review]
Looks good, just left a few comments

**Review by rdormer — APPROVED** [review]

**Comment by etagwerker** [comment]
@bronzdoc I addressed your comments 👍

**Review by bronzdoc — APPROVED** [review]

**Pull request merged**
