### PR TITLE
Config webpacker and yarn

### PR DESCRIPTION
**Pull request by arielj**
Closing https://github.com/fastruby/skunk.fyi/issues/1

This PR adds the proper Webpacker config to use Webpack to manage the javascript code, adds the styleguide as a node module and fixes the sprocket's config to read the CSS of the styleguide from the node_modules dir.

Changes:
- Added Webpacker gem and its config
- Removed `fastruby-styleguide` gem
- Added the `application.js` script tag
- Fixed `assets_path` config variable to read the `fastruby-io-styleguide` assets from node_modules
- Added Webpack config to expose jQuery globally
- Replaced `jquery_ujs` with `rails-ujs`
- Added the `yarn install` command during travisci run

NOTE:
~Since the PR for the styleguide is not yet merged, the yarn package added points to the branch of that PR, after that PR gets merged we have to update the package to use the `gh-pages` branch instead.~

EDIT: I already applied the change on the previous note

EDIT:

> Depending on the order of how the current PRs are merged, one of them will need to update the CircleCI config to add the `yarn install` command after this line https://github.com/fastruby/skunk.fyi/pull/8/files#diff-221ebe6de14f27739a14874b41c734ae79930dd4fdbb59c06289e856632120a7R37

### CODE REVIEW

**Comment by arielj** [comment]
@etagwerker I saw you tagged this as a good first issue, but this is actually the PR for that issue

**Comment by etagwerker** [comment]
@arielj I meant to tag it because I think it would be great if someone (other than me) can review the PR and test it in their local environment. 😄

**Comment by FionaDL** [comment]
@arielj  I think it would be a good idea to add `yarn install` to the ./bin/setup or the README.

**Comment by arielj** [comment]
@FionaDL done!

**Comment by arielj** [comment]
Added a comment related to the `yarn install` command and the CircleCI config, I can't add that here because the CircleCI config is in another branch, so depending on which branch is merged first, the other branch will have to update the CircleCI config.

**Comment by bronzdoc** [comment]
@arielj How can I test this? I gave this a look yesterday, i bundled and ran yarn install and started the server and everything works fine. Do I need to do something in specific?

**Comment by bronzdoc** [comment]
Well I created a simple test.js file to console.log some stuff  and then imported it in packs/application.js and it works. 

Screen Shot 2020-10-30 at 7 52 46 AM

**Review by bronzdoc — APPROVED** [review]

**Pull request merged**
